apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: promop
  namespace: promop
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~0
spec:
  releaseName: promop
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-operator
    version: 5.15.0