apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: istio
  namespace: istio-system
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: istio
  chart:
    repository: https://storage.googleapis.com/istio-release/releases/1.2.2/charts
    name: istio
    version: 1.2.2
  values:
    #
    # addon grafana configuration
    #
    grafana:
      enabled: true